parameters:
  users_base_url: 'http://localhost:9080'
  test_authentication_provider_bundle_frontend_token_provider_users:
    'user1@example.com': 'password'
    'user2@example.com': 'password'
  test_authentication_provider_bundle_users_url: 'http://localhost:9080'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Psr\Http\Client\ClientInterface:
    class: GuzzleHttp\Client
