parameters:
    test_authentication_provider_bundle_frontend_token_provider_users: []

services:
    _defaults:
        autowire: true
        autoconfigure: true

    SmartAssert\ServiceClient\ExceptionFactory\CurlExceptionFactory: ~

    SmartAssert\TestAuthenticationProviderBundle\FrontendTokenProvider:
        arguments:
            $userCredentials: '%test_authentication_provider_bundle_frontend_token_provider_users%'
        public: true

    SmartAssert\TestAuthenticationProviderBundle\UserProvider:
        public: true

    SmartAssert\TestAuthenticationProviderBundle\ApiTokenProvider:
        public: true
